# Generated by Django 4.0.3 on 2022-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('job_title', models.CharField(blank=True, max_length=50)),
                ('job_summary', models.CharField(blank=True, max_length=150)),
                ('birthday', models.DateField(blank=True, max_length=20)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('age', models.CharField(blank=True, max_length=5)),
                ('degree', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=25)),
                ('freelance', models.CharField(blank=True, max_length=20)),
                ('about_summary', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
