# Generated by Django 4.0.3 on 2022-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_resume', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=30)),
                ('about_myself', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=25)),
                ('master_major_name', models.CharField(blank=True, max_length=50)),
                ('master_major_durations', models.CharField(blank=True, max_length=15)),
                ('master_major_institute_name', models.CharField(blank=True, max_length=50)),
                ('about_master_institute', models.CharField(blank=True, max_length=150)),
                ('bachelor_major_name', models.CharField(blank=True, max_length=50)),
                ('bachelor_major_durations', models.CharField(blank=True, max_length=15)),
                ('bachelor_major_institute_name', models.CharField(blank=True, max_length=50)),
                ('bachelor_master_institute', models.CharField(blank=True, max_length=150)),
                ('current_job_position_title', models.CharField(blank=True, max_length=50)),
                ('current_job_job_year', models.CharField(blank=True, max_length=10)),
                ('current_job_job_city', models.CharField(blank=True, max_length=25)),
                ('current_job_job_about', models.TextField(max_length=1000)),
                ('old_job_position_title', models.CharField(blank=True, max_length=50)),
                ('old_job_job_year', models.CharField(blank=True, max_length=10)),
                ('old_job_job_city', models.CharField(blank=True, max_length=25)),
                ('old_job_job_about', models.TextField(max_length=1000)),
            ],
        ),
    ]
