# Generated by Django 4.0.3 on 2022-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_contact', models.TextField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_services', models.TextField(blank=True, max_length=200)),
                ('service_1st', models.CharField(blank=True, max_length=50)),
                ('about_service_1st', models.TextField(blank=True, max_length=100)),
                ('service_2nd', models.CharField(blank=True, max_length=50)),
                ('about_service_2nd', models.TextField(blank=True, max_length=100)),
                ('service_3rd', models.CharField(blank=True, max_length=50)),
                ('about_service_3rd', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
