# Generated by Django 4.0.3 on 2022-03-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
