# Generated by Django 4.0.3 on 2022-03-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Login', '0002_rename_is_acitve_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_stuff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Is only for admin', verbose_name='Staff Status'),
        ),
    ]
